### ISSUE TITLE
Move links to SciServer tools into Web.config

### ISSUE THREAD

**Issue by raddick** [idies/sciserver-sso-portal#18]
On the current login portal:

http://scitest02.pha.jhu.edu/login-portal/

The links to the "SciServer Tools" in the right-hand menu are hard-coded to point to scitest02 . But since we will have different login portals on the dev/test/production sites, it would be good to retrieve these links from Web.config so we can use the same code on whatever site we need. (This is how we get external links on SkyServer and CasJobs.)

I have added the following lines into the Web.config in my "raddick" web space on scidev03:

```
    <add key="WindowsServer" value="//scitest02.pha.jhu.edu/" />
    <add key="LinuxServer" value="//scitest09.pha.jhu.edu" />
```

But I don't know enough about Views to know how to update the code in Views/Shares/SciServerTools.cshtml to retrieve the new values from Web.config. I played around with it for an hour but couldn't get it to work.

Not sure who is right to assign this to, so assigning it to @bonbons0220 for the moment.

**Comment by bonbons0220** [comment]
Having a look now...

Bonnie Souter PhD

Web Developer for IDIES and SDSS

Dept of Physics and Astronomy Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by bonbons0220** [comment]
I think the only reason why these are pointing to scitest02 and scitest09
is so that the links are valid. It's probably my fault, of course.

There is actually no reason why these links should point to anything other
that the production version of SkyServer, CasJobs and SciDrive.

Both SkyServer and CasJobs already have prod websites and therefore valid
links: skyserver.sdss.org & skyserver.sdss.org/CasJobs/

What is/will be the link for SciDrive?


Bonnie Souter PhD

Web Developer for IDIES and SDSS

Dept of Physics and Astronomy Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by raddick** [comment]
It's helpful to be able to set these links to point to whichever site is most appropriate for a given application. That way, we can have the e.g. production SkyServer pointing to the production portal, the test SkyServer pointing to the test portal, and the raddick dev SkyServer pointing to the raddick dev portal.

I think getting the links out of Web.config, and having a different Web.config for each site, is the easiest way to make that happen.

**Comment by bonbons0220** [comment]
With all due respect, I disagree.

I just don't see the point of linking from the test version of the portal
to the test version of other webapps on a nav menu. They are separate but
related webapps. These are just links in a nav menu, not part of intrinsic
functionality. It would be like linking to test.skyserver.org from
test.sciserver.org, instead of linking to the real skyserver.

In your most recent email you talk about linking *to* the portal, not
linking *from* the portal . You don't really need to link *to* an app from
the portal, right? Clicking on a link to any version of the portal should
send you back wherever you came from when you're done logging in, right? So
is there a need to specify which version to return to? The Return URL is
passed in to the portal as a variable, right?

Also, bear in mind that we will have private repos within a few weeks or
months. Someone might decide: hey, let's check in the Web.config file now
that it's a private repo.

Anyhow, I guess it all depends on the test scripts, and integration test
scripts.

Cheers,
Bonnie


Bonnie Souter PhD

Web Developer for IDIES and SDSS

Dept of Physics and Astronomy Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by thakar** [comment]
I guess it depends on whether the dev/test/prod environments include all
the sciserver apps or only some of them.  I believe it is the former
because we generally test them all together, i.e. when you are using the
portal on the test server (scitest02), you want it to link to the
skyserver/casjobs on the test server rather than the production ones,
right?  Similarly, when you are using the portal on the dev server
(scidev03), I presume you want to link to the apps on the dev server.

    Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Those who can make you believe absurdities can make you commit
atrocities. [Voltaire]

**Comment by bonbons0220** [comment]
You can also check the _SERVER environment variable to decide which site to
link to.

Bonnie Souter PhD

Web Developer for IDIES and SDSS

Dept of Physics and Astronomy Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by raddick** [comment]
I think the solution that @bonbons0220 and I discussed this morning is the right solution: have a parameter in web.config that sets the environment as one of {dev,test,prod}. Then have logic in the code somewhere (maybe lower down in web.config?) that sets the appropriate servers to link to for those three environments. The logic should always fail-safe to set up links for the production environment.

Looks like this has morphed into a different feature request, so lemme close this issue and file another one.
